---
agriculture_file : "landbouw_per_provincie.csv"
bird_file : "trends_broedvogels_1990-2020_sovon.csv"
Greater Canada Goose : "Greater Canada Goose.png"
Barnacle Goose : "Barnacle Goose.png"
Greylag Goose : "Greylag Goose.png"
Mute Swan : "Mute Swan.png"
Egyptian Goose : "Egyptian Goose.png"
Common Shelduck : "Common Shelduck.png"
Garganey : "Garganey.png"
Northern Shoveler : "Northern Shoveler.png"
Gadwall : "Gadwall.png"
Mallard : "Mallard.png"
Feral Mallard : "Feral Mallard.png"
Eurasian Teal : "Eurasian Teal.png"
Red-crested Pochard : "Red-crested Pochard.png"
Common Pochard : "Common Pochard.png"
Tufted Duck : "Tufted Duck.png"
Common Eider : "Common Eider.png"
Red-breasted Merganser : "Red-breasted Merganser.png"
Black Grouse : "Black Grouse.png"
Grey Partridge : "Grey Partridge.png"
Common Quail : "Common Quail.png"
Common Pheasant : "Common Pheasan.png"
Little Grebe : "Little Grebe.png"
Great Crested Grebe : "Great Crested Grebe.png"
Black-necked Grebe : "Black-necked Grebe.png"
White Stork : "White Stork.png"
Eurasian Spoonbill : "Eurasian Spoonbill.png"
Eurasian Bittern : "Eurasian Bittern.png"
Grey Heron : "Grey Heron.png"
Purple Heron : "Purple Heron.png"